using DbScriptReader.Analyzers;
using System.Data;

namespace DbScriptReader
{
    /// <summary>
    /// Helper class that handles additional methods generated by <see cref="MethodGenerator"/>.
    /// </summary>
    public static class DbScriptReaderHandler
    {
        /// <summary>
        /// Invokes <paramref name="action"/> on database connection provided by <paramref name="instance"/>.
        /// Optionally disposes of this connection if returned value has its <c>Dispose</c> flag set.
        /// </summary>
        /// <typeparam name="T">Type of value to return.</typeparam>
        /// <param name="instance">Instance on which to perform <paramref name="action"/>.</param>
        /// <param name="action">Action to perform on <paramref name="instance"/>.</param>
        /// <returns>Result of <paramref name="action"/> invokation.</returns>
        public static T Invoke<T>(IDbScriptReader instance, Func<IDbConnection, T> action)
        {
            (IDbConnection connection, bool dispose) = instance.GetConnection();

            if (!dispose)
                return action.Invoke(connection);

            using (connection)
                return action.Invoke(connection);
        }

        /// <summary>
        /// Invokes <paramref name="action"/> on database connection provided by <paramref name="instance"/>.
        /// Optionally disposes of this connection if returned value has its <c>Dispose</c> flag set.
        /// Note that enumerables should be buffered as this method exits without explicitly enumerating them.
        /// </summary>
        /// <typeparam name="T">Type of value to return.</typeparam>
        /// <param name="instance">Instance on which to perform <paramref name="action"/>.</param>
        /// <param name="action">Action to perform on <paramref name="instance"/>.</param>
        /// <returns>Result of <paramref name="action"/> invokation.</returns>
        public static async Task<T> InvokeAsync<T>(IDbScriptReader instance, Func<IDbConnection, Task<T>> action)
        {
            (IDbConnection connection, bool dispose) = instance.GetConnection();

            if (!dispose)
                return await action.Invoke(connection);

            using (connection)
                return await action.Invoke(connection);
        }
    }
}
